const fs = require('fs');
const words = JSON.parse(fs.readFileSync('words.json', 'utf8'));

const batch = [
  // Step 5: Günlük Rutin
  {tr: 'Uyanmak', uz: "Uyg'onmoq", ex: 'Her sabah yedide uyanırım.', step: 5},
  {tr: 'Kalkmak', uz: 'Turmoq', ex: 'Yataktan erken kalktım.', step: 5},
  {tr: 'Yıkamak', uz: 'Yuvmoq', ex: 'Sabah yüzümü soğuk suyla yıkarım.', step: 5},
  {tr: 'Fırçalamak', uz: 'Tozalamoq (Cho\'tkalamoq)', ex: 'Dişlerimi günde iki kez fırçalarım.', step: 5},
  {tr: 'Hazırlanmak', uz: 'Tayyorlanmoq', ex: 'İşe gitmek için hazırlanıyorum.', step: 5},
  {tr: 'Giyinmek', uz: 'Kiyinmoq', ex: 'Okul için hızlıca giyindim.', step: 5},
  {tr: 'Çıkmak', uz: 'Chiqmoq', ex: 'Saat sekizde evden çıkarım.', step: 5},
  {tr: 'Binmek', uz: 'Minmoq', ex: 'Otobüse her zaman vaktinde binerim.', step: 5},
  {tr: 'Beklemek', uz: 'Kutmoq', ex: 'Durdakta on-beş dakika bekledim.', step: 5},
  {tr: 'Çalışmak', uz: 'İshlamoq (O\'qimoq)', ex: 'Öğleden sonra kütüphanede çalışırız.', step: 5},
  {tr: 'Öğrenmek', uz: 'O\'rganmoq', ex: 'Yeni kelimeler öğrenmeyi seviyorum.', step: 5},
  {tr: 'Dinlenmek', uz: 'Dam olmoq', ex: 'İşten sonra biraz dinlenmek lazım.', step: 5},
  {tr: 'Okumak', uz: 'O\'qimoq', ex: 'Yatmadan önce kitap okurum.', step: 5},
  {tr: 'İzlemek', uz: 'Ko\'rmoq (Tomosha qilmoq)', ex: 'Bu akşam güzel bir film izleyeceğiz.', step: 5},
  {tr: 'Uyumak', uz: 'Uxlamoq', ex: 'Erken uyumak kalbe iyi gelir.', step: 5},
  {tr: 'Rüya', uz: 'Tush', ex: 'Dün gece çok ilginç bir rüya gördüm.', step: 5},
  {tr: 'Yürüyüş', uz: 'Sayr (Piyoda yurish)', ex: 'Hafta sonları ormanda yürüyüş yaparız.', step: 5},
  {tr: 'Spor', uz: 'Sport', ex: 'Sağlıklı yaşam için spor çok önemlidir.', step: 5},
  {tr: 'Alışveriş', uz: 'Xarid qilish', ex: 'Annemle çarşıya alışverişe gittik.', step: 5},
  {tr: 'Temizlik', uz: 'Tozalash', ex: 'Bugün tüm evi tek başıma temizledim.', step: 5},
  {tr: 'Misafir', uz: 'Mehmon', ex: 'Yarın akşam evimize misafir gelecek.', step: 5},
  {tr: 'Sohbet', uz: 'Suhbat', ex: 'Arkadaşımla uzun uzun sohbet ettik.', step: 5},
  {tr: 'Telefon', uz: 'Telefon', ex: 'Beni akşam saat dokuzda ara.', step: 5},
  {tr: 'Pazar', uz: 'Bozor', ex: 'Pazardan taze sebze ve meyve aldık.', step: 5},
  {tr: 'Buluşmak', uz: 'Uchrashmoq', ex: 'Arkadaşlarla kafede buluştuk.', step: 5},

  // Step 6: Vücut ve Sağlık
  {tr: 'Baş', uz: 'Bosh', ex: 'Başım çok ağrıyor, biraz uyumalıyım.', step: 6},
  {tr: 'Göz', uz: 'Ko\'z', ex: 'Doktor gözlerimi kontrol etti.', step: 6},
  {tr: 'Kulak', uz: 'Quloq', ex: 'Kulağımda hafif bir ağrı var.', step: 6},
  {tr: 'Burun', uz: 'Burun', ex: 'Hava soğuk olduğu için burnum aktı.', step: 6},
  {tr: 'Ağız', uz: 'Og\'iz', ex: 'Ağzını büyükçe açıp nefes aldı.', step: 6},
  {tr: 'Diş', uz: 'Tish', ex: 'Dişçi dişimdeki çürüğü temizledi.', step: 6},
  {tr: 'Dil', uz: 'Til', ex: 'Diliyle dudaklarını ıslattı.', step: 6},
  {tr: 'Boğaz', uz: 'Tomoq', ex: 'Soğuk su içince boğazım şişti.', step: 6},
  {tr: 'Boyun', uz: 'Bo\'yin', ex: 'Yastık çok sert, boynum tutuldu.', step: 6},
  {tr: 'Omuz', uz: 'Yelka', ex: 'Çantayı omzuna astı.', step: 6},
  {tr: 'El', uz: 'Qo\'l', ex: 'Yemekten önce ellerini sabunla yıka.', step: 6},
  {tr: 'Parmak', uz: 'Barmoq', ex: 'Top oynarken parmağım incindi.', step: 6},
  {tr: 'Bacak', uz: 'Oyoq (son)', ex: 'Bugün çok yürüdüm, bacaklarım ağrıdı.', step: 6},
  {tr: 'Ayak', uz: 'Oyoq (panja)', ex: 'Yeni ayakkabılar ayağımı sıktı.', step: 6},
  {tr: 'Kalp', uz: 'Yurak', ex: 'Heyecandan kalbim hızla çarpıyor.', step: 6},
  {tr: 'Mide', uz: 'Oshqozon', ex: 'Midem bulanıyor, bir nane çayı içmeliyim.', step: 6},
  {tr: 'Hastane', uz: 'Kasalxona', ex: 'En yakın hastane iki sokak ötede.', step: 6},
  {tr: 'Doktor', uz: 'Shifokor', ex: 'Doktora gidip muayene oldum.', step: 6},
  {tr: 'İlaç', uz: 'Dori', ex: 'Bu ilacı her sabah içmelisin.', step: 6},
  {tr: 'Eczane', uz: 'Dorixona', ex: 'Eczaneden ağrı kesici aldım.', step: 6},
  {tr: 'Ateş', uz: 'Isitma', ex: 'Çocuğun ateşi çok yüksek.', step: 6},
  {tr: 'Nezle', uz: 'Gripp (Shamollash)', ex: 'Nezle olduğum için çok hapşırıyorum.', step: 6},
  {tr: 'Randevu', uz: 'Uchrashuv', ex: 'Yarın doktor randevum var.', step: 6},
  {tr: 'Reçete', uz: 'Retsept', ex: 'Doktor bana bir reçete yazdı.', step: 6},
  {tr: 'Muayene', uz: 'Tekshiruv', ex: 'Genel bir sağlık muayenesi yaptırdım.', step: 6},

  // Step 7: Kıyafetler ve Alışveriş
  {tr: 'Gömlek', uz: 'Ko\'ylak', ex: 'Bugün beyaz bir gömlek giymişti.', step: 7},
  {tr: 'Pantolon', uz: 'Shim', ex: 'Yeni pantolonu ona çok yakışmış.', step: 7},
  {tr: 'Ceket', uz: 'Kiyim (Ko\'ylak)', ex: 'Hava soğuk, ceketini almayı unutma.', step: 7},
  {tr: 'Elbise', uz: 'Ko\'ylak (Ayollar)', ex: 'Düğün için çok şık bir elbise aldı.', step: 7},
  {tr: 'Etek', uz: 'Yubka', ex: 'Puanlı pembe eteği çok sevimliydi.', step: 7},
  {tr: 'Ayakkabı', uz: 'Oyoq kiyim', ex: 'Spor ayakkabılarım çok rahat.', step: 7},
  {tr: 'Şapka', uz: 'Shlyapa (Qalpoq)', ex: 'Güneşten korunmak için şapka taktı.', step: 7},
  {tr: 'Eldiven', uz: 'Qo\'lqop', ex: 'Kışın ellerimi sıcak tutmak için eldiven giyerim.', step: 7},
  {tr: 'Atkı', uz: 'Sharf', ex: 'Boynuna uzun gri bir atkı doladı.', step: 7},
  {tr: 'Çorap', uz: 'Paypoq', ex: 'Renkli çoraplar giymeyi çok severim.', step: 7},
  {tr: 'Kuşak / Kemer', uz: 'Kamar', ex: 'Pantolonu düşmesin diye kemer taktı.', step: 7},
  {tr: 'Gözlük', uz: 'Ko\'zoynak', ex: 'Kitap okurken gözlük kullanmak zorundayım.', step: 7},
  {tr: 'Saat', uz: 'Soat', ex: 'Kol saati durmuş, pilini değiştirmeliyim.', step: 7},
  {tr: 'Cüzdan', uz: 'Hamyon', ex: 'Parasını cüzdanına koydu.', step: 7},
  {tr: 'Market', uz: 'Do\'kon (Bozor)', ex: 'Marketten süt ve yumurta almalıyım.', step: 7},
  {tr: 'Fiyat', uz: 'Narx', ex: 'Bu gömleğin fiyatı ne kadar?', step: 7},
  {tr: 'İndirim', uz: 'Chegirma', ex: 'Mağazada %50 indirim varmış.', step: 7},
  {tr: 'Pahalı', uz: 'Qimmat', ex: 'Bu araba benim için çok pahalı.', step: 7},
  {tr: 'Ucuz', uz: 'Arzon', ex: 'Pazardan çok ucuz meyveler aldık.', step: 7},
  {tr: 'Yeni', uz: 'Yangi', ex: 'Yeni evimiz parka çok yakın.', step: 7},
  {tr: 'Eski', uz: 'Eski', ex: 'Eski eşyalarımı kutuya koydum.', step: 7},
  {tr: 'Büyük', uz: 'Katta', ex: 'Bu oda çok büyük, her şey sığar.', step: 7},
  {tr: 'Küçük', uz: 'Kichik', ex: 'Küçük bir kasabada yaşıyoruz.', step: 7},
  {tr: 'Güzel', uz: 'Go\'zal', ex: 'Hava bugün çok güzel, dışarı çıkalım.', step: 7},
  {tr: 'Çirkin', uz: 'Xunuk', ex: 'Çirkin ördek yavrusu masalını biliyor musun?', step: 7},

  // Step 8: Zaman ve Mevsimler
  {tr: 'Zaman', uz: 'Vaqt', ex: 'Zaman su gibi akıp gidiyor.', step: 8},
  {tr: 'Dakika', uz: 'Daqiqa', ex: 'Beş dakika içinde orada olacağım.', step: 8},
  {tr: 'Saat', uz: 'Soat', ex: 'Film iki saat sürdü.', step: 8},
  {tr: 'Gün', uz: 'Kun', ex: 'Bugün çok yorucu bir gündü.', step: 8},
  {tr: 'Hafta', uz: 'Hafta', ex: 'Gelecek hafta tatile gidiyoruz.', step: 8},
  {tr: 'Ay', uz: 'Oy', ex: 'Yılın ilk ayı Ocak ayıdır.', step: 8},
  {tr: 'Yıl', uz: 'Yil', ex: 'Yeni yılın kutlu olsun!', step: 8},
  {tr: 'Bugün', uz: 'Bugun', ex: 'Bugün sabah erkenden uyandım.', step: 8},
  {tr: 'Dün', uz: 'Kecha', ex: 'Dün akşam tiyatroya gittik.', step: 8},
  {tr: 'Yarın', uz: 'Ertaga', ex: 'Yarın kütüphanede buluşalım.', step: 8},
  {tr: 'Sabah', uz: 'Ertalab', ex: 'Sabahları koşu yapmayı severim.', step: 8},
  {tr: 'Öğle', uz: 'Tush (kun)', ex: 'Öğle sıcağında dışarı çıkmayın.', step: 8},
  {tr: 'Akşam', uz: 'Kech (Oqshom)', ex: 'Akşam yemeğine misafir gelecek.', step: 8},
  {tr: 'Gece', uz: 'Tun', ex: 'Gece gökyüzü yıldızlarla doluydu.', step: 8},
  {tr: 'Şimdi', uz: 'Hozir', ex: 'Şimdi ödevlerimi yapıyorum.', step: 8},
  {tr: 'Sonra', uz: 'Keyin', ex: 'Önce yemek yiyelim, sonra konuşuruz.', step: 8},
  {tr: 'Önce', uz: 'Avval', ex: 'Gitmelerinden önce vedalaşmalıyız.', step: 8},
  {tr: 'Erken', uz: 'Erta', ex: 'Bugün işe erken gittim.', step: 8},
  {tr: 'Geç', uz: 'Kech', ex: 'Trafik yüzünden eve geç geldim.', step: 8},
  {tr: 'İlkbahar', uz: 'Bahor', ex: 'İlkbaharda her yer çiçek açar.', step: 8},
  {tr: 'Yaz', uz: 'Yoz', ex: 'Yazın tatile gitmeyi planlıyoruz.', step: 8},
  {tr: 'Sonbahar', uz: 'Kuz', ex: 'Sonbaharda yapraklar sararır.', step: 8},
  {tr: 'Kış', uz: 'Qish', ex: 'Kışın burada çok kar yağar.', step: 8},
  {tr: 'Ocak', uz: 'Yanvar', ex: 'Ocak ayı çok soğuk geçiyor.', step: 8},
  {tr: 'Aralık', uz: 'Dekabr', ex: 'Aralık ayı yılın son ayıdır.', step: 8},

  // Step 9: Meslekler ve İş
  {tr: 'Öğretmen', uz: 'O\'qituvchi', ex: 'Babam lisede matematik öğretmeni.', step: 9},
  {tr: 'Mühendis', uz: 'Muhandis', ex: 'Ablam inşaat mühendisi oldu.', step: 9},
  {tr: 'Mimar', uz: 'Me\'mor', ex: 'Yeni evi bir mimar çizdi.', step: 9},
  {tr: 'Avukat', uz: 'Advokat', ex: 'Hukuki işler için bir avukat tuttuk.', step: 9},
  {tr: 'Polis', uz: 'Politsiyachi', ex: 'Polis trafiği düzenliyor.', step: 9},
  {tr: 'Asker', uz: 'Askariya (Askariya)', ex: 'Abim askere gitti.', step: 9},
  {tr: 'Esnaf', uz: 'Savatli (Xalqaro savdogar)', ex: 'Mahalle esnafını çok severiz.', step: 9},
  {tr: 'Müdür', uz: 'Muddir (Boshliq)', ex: 'Toplantıyı şirket müdürü yönetti.', step: 9},
  {tr: 'Sekreter', uz: 'Kotiba', ex: 'Randevu için sekreterle görüştük.', step: 9},
  {tr: 'Şoför', uz: 'Haydovchi', ex: 'Taksi şoförü yolu çok iyi biliyor.', step: 9},
  {tr: 'Aşçı', uz: 'Oshpaz', ex: 'Aşçı çok lezzetli yemekler yapmış.', step: 9},
  {tr: 'İşçi', uz: 'Ishchi', ex: 'Fabrikada birçok işçi çalışıyor.', step: 9},
  {tr: 'Emekli', uz: 'Nafaqaxur (Pensioner)', ex: 'Dedem geçen yıl emekli oldu.', step: 9},
  {tr: 'Öğrenci', uz: 'Talaba (O\'quvchi)', ex: 'Üniversite öğrencileri ders çalışıyor.', step: 9},
  {tr: 'Bilgisayar', uz: 'Kompyuter', ex: 'Ödevimi bilgisayarda yapıyorum.', step: 9},
  {tr: 'İnternet', uz: 'Internet', ex: 'Bugün internette sorun var.', step: 9},
  {tr: 'E-posta', uz: 'Elektron pochta', ex: 'Sana bir e-posta gönderdim.', step: 9},
  {tr: 'Toplantı', uz: 'Majlis (Uchrashuv)', ex: 'Az sonra önemli bir toplantımız var.', step: 9},
  {tr: 'Maaş', uz: 'Maosh', ex: 'Mesai bitince maaşımı alacağım.', step: 9},
  {tr: 'Tatil', uz: 'Ta\'til', ex: 'Yaz tatilinde Marmaris\'e gideceğiz.', step: 9},
  {tr: 'Yorgun', uz: 'Charchagan', ex: 'İşten sonra çok yorgun hissediyorum.', step: 9},
  {tr: 'Meşgul', uz: 'Band', ex: 'Şu an meşgulüm, sonra ara.', step: 9},
  {tr: 'Boş zaman', uz: 'Bo\'sh vaqt', ex: 'Boş zamanımda resim yaparım.', step: 9},
  {tr: 'Başarı', uz: 'Muvaffaqiyat', ex: 'Azimli olmak başarı getirir.', step: 9},
  {tr: 'Hedef', uz: 'Maqsad', ex: 'Bu yılki hedefim Türkçe öğrenmek.', step: 9},

  // Step 10: Ev ve Eşyalar
  {tr: 'Sandalye', uz: 'Stul', ex: 'Lütfen masanın başındaki sandalyeye otur.', step: 10},
  {tr: 'Masa', uz: 'Stol', ex: 'Masanın üzerine vazoyu koydum.', step: 10},
  {tr: 'Koltuk', uz: 'O\'rindiq (Divan)', ex: 'Yeni koltuk takımımız çok rahat.', step: 10},
  {tr: 'Yatak', uz: 'Yotoq', ex: 'Yatağına yatıp hemen uyudu.', step: 10},
  {tr: 'Perde', uz: 'Parda', ex: 'Güneş gelmesin diye perdeleri kapattım.', step: 10},
  {tr: 'Halı', uz: 'Gilam', ex: 'Yere yumuşak tüylü bir halı serdik.', step: 10},
  {tr: 'Lamba', uz: 'Lampa', ex: 'Odayı aydınlatmak için lambayı açtım.', step: 10},
  {tr: 'Ayna', uz: 'Oyna (Ko\'zgu)', ex: 'Aynada kendine bakıp saçını taradı.', step: 10},
  {tr: 'Buzdolabı', uz: 'Sovutgich (Muzlatgich)', ex: 'Yemekleri buzdolabına koyduk.', step: 10},
  {tr: 'Fırın', uz: 'Pech', ex: 'Keki fırına verip beklemeye başladık.', step: 10},
  {tr: 'Televizyon', uz: 'Televizor', ex: 'Haberleri televizyondan izledik.', step: 10},
  {tr: 'Bilgisayar', uz: 'Kompyuter', ex: 'Oyun oynamak için bilgisayarı açtı.', step: 10},
  {tr: 'Telefon', uz: 'Telefon', ex: 'Telefonum çantanın içinde çalıyor.', step: 10},
  {tr: 'Yastık', uz: 'Yostiq', ex: 'Boynu ağrımasın diye yumuşak bir yastık aldı.', step: 10},
  {tr: 'Battaniye', uz: 'Adyol', ex: 'Kışın battaniyenin altında film izlemek güzel.', step: 10},
  {tr: 'Tabak', uz: 'Lagan (Tovoq)', ex: 'Yemeği tabağına özenle koydu.', step: 10},
  {tr: 'Bardak', uz: 'Stakan', ex: 'Bir bardak taze portakal suyu içtim.', step: 10},
  {tr: 'Çatal', uz: 'Sanchqi', ex: 'Makarna yemek için çatal kullandı.', step: 10},
  {tr: 'Bıçak', uz: 'Pichoq', ex: 'Ekmeği keskin bir bıçakla dilimledi.', step: 10},
  {tr: 'Kaşık', uz: 'Qoshiq', ex: 'Çorbayı gümüş renkli bir kaşıkla içti.', step: 10},
  {tr: 'Pencere', uz: 'Deraza', ex: 'Manzarayı izlemek için pencereyi açtı.', step: 10},
  {tr: 'Kapı', uz: 'Eshik', ex: 'Kimse gelmesin diye kapıyı kilitledi.', step: 10},
  {tr: 'Duvar', uz: 'Devor', ex: 'Duvarı boydan boya beyaza boyadık.', step: 10},
  {tr: 'Tavan', uz: 'Shift', ex: 'Odanın tavanı çok yüksekti.', step: 10},
  {tr: 'Zemin', uz: 'Zamin (Pol)', ex: 'Islak zemin üzerinde yürümemelisin.', step: 10},

  // Step 11: Doğa ve Hava Durumu
  {tr: 'Doğa', uz: 'Tabiat', ex: 'Doğayı sevmek insanlığı sevmektir.', step: 11},
  {tr: 'Dağ', uz: 'Tog\'', ex: 'Hafta sonu dağ yürüyüşüne gideceğiz.', step: 11},
  {tr: 'Deniz', uz: 'Dengiz', ex: 'Yazın denizde yüzmeyi çok severim.', step: 11},
  {tr: 'Nehir', uz: 'Daryo', ex: 'Nehir kıyısında piknik yaptık.', step: 11},
  {tr: 'Göl', uz: 'Ko\'l', ex: 'Gölün suyu çok temiz ve durgun.', step: 11},
  {tr: 'Orman', uz: 'O\'rmon', ex: 'Ormanda temiz hava aldık.', step: 11},
  {tr: 'Ağaç', uz: 'Daraxt', ex: 'Bahçeye kiraz ağacı diktik.', step: 11},
  {tr: 'Çiçek', uz: 'Gul', ex: 'Vazo için taze çiçekler topladım.', step: 11},
  {tr: 'Güneş', uz: 'Quyosh', ex: 'Güneş bulutların arasından parlıyor.', step: 11},
  {tr: 'Ay', uz: 'Oy', ex: 'Gece gökyüzünde hilal şeklinde ay vardı.', step: 11},
  {tr: 'Yıldız', uz: 'Yulduz', ex: 'Yıldızları izlemek huzur verici.', step: 11},
  {tr: 'Bulut', uz: 'Bulut', ex: 'Kara bulutlar yağmurun habercisi.', step: 11},
  {tr: 'Yağmur', uz: 'Yomg\'ir', ex: 'Yağmur yağarken yürümeyi severim.', step: 11},
  {tr: 'Kar', uz: 'Qor', ex: 'Çocuklar karla oynamak için dışarı çıktı.', step: 11},
  {tr: 'Rüzgar', uz: 'Shamol', ex: 'Sert rüzgar yaprakları savurdu.', step: 11},
  {tr: 'Sıcak', uz: 'Issiq', ex: 'Bugün hava gerçekten çok sıcak.', step: 11},
  {tr: 'Soğuk', uz: 'Sovuq', ex: 'Soğuk havalarda kalın giyinmelisin.', step: 11},
  {tr: 'Ilık', uz: 'Iliq', ex: 'Baharda hava ne sıcak ne soğuk, ılıktır.', step: 11},
  {tr: 'Nemli', uz: 'Namli (Rütubatli)', ex: 'Deniz kenarı olduğu için hava nemli.', step: 11},
  {tr: 'Kurak', uz: 'Quruq', ex: 'Bu bölgemizde toprak çok kuraktır.', step: 11},
  {tr: 'Şimşek', uz: 'Chaqmoq', ex: 'Gök gürültüsünden sonra şimşek çaktı.', step: 11},
  {tr: 'Fırtına', uz: 'Bo\'ron', ex: 'Denizde büyük bir fırtına çıktı.', step: 11},
  {tr: 'Mevsim', uz: 'Fasl', ex: 'En sevdiğim mevsim ilkbahardır.', step: 11},
  {tr: 'Çevre', uz: 'Atrof-muhit', ex: 'Çevremizi temiz tutmalıyız.', step: 11},
  {tr: 'Gökkuşağı', uz: 'Kamalak', ex: 'Yağmurdan sonra harika bir gökkuşağı belirdi.', step: 11},

  // Step 12: Duygular ve İlişkiler
  {tr: 'Mutlu', uz: 'Baxtiyor', ex: 'Seni gördüğüm için çok mutluyum.', step: 12},
  {tr: 'Üzgün', uz: 'Xafa', ex: 'Sınavı geçemediği için üzgün görünüyor.', step: 12},
  {tr: 'Kızgın', uz: 'G\'azablangan', ex: 'Yalan söylediğin için bana kızgın mısın?', step: 12},
  {tr: 'Korkmuş', uz: 'Qo\'rqqan', ex: 'Karanlıktan korkmuş bir çocuk gibiydi.', step: 12},
  {tr: 'Şaşırmış', uz: 'Hayron qolgan', ex: 'Hediyeyi görünce çok şaşırmış.', step: 12},
  {tr: 'Heyecanlı', uz: 'Hayajonlangan', ex: 'Yarınki gezi için çok heyecanlıyım.', step: 12},
  {tr: 'Sakin', uz: 'Xotirjam', ex: 'Deniz kenarında oturmak insanı sakinleştirir.', step: 12},
  {tr: 'Yorgun', uz: 'Charchagan', ex: 'Çok çalıştım, bu akşam çok yorgunum.', step: 12},
  {tr: 'Uykulu', uz: 'Uyqusiragan', ex: 'Sabah erkenden kalktığı için uykulu.', step: 12},
  {tr: 'Sıkılmış', uz: 'Zarıkkan', ex: 'Evde oturmaktan çok sıkılmış.', step: 12},
  {tr: 'Yalnız', uz: 'Yolg\'iz', ex: 'Kendimi bazen çok yalnız hissediyorum.', step: 12},
  {tr: 'Aşık', uz: 'Oshiq', ex: 'Genç adam kıza ilk görüşte aşık oldu.', step: 12},
  {tr: 'Sevgi', uz: 'Sevgi', ex: 'Sevgi her kapıyı açar.', step: 12},
  {tr: 'Nefret', uz: 'Nafrat', ex: 'Kalbinde hiç nefret barındırma.', step: 12},
  {tr: 'Güven', uz: 'Ishonch', ex: 'İlişkide güven en önemli unsurdur.', step: 12},
  {tr: 'Korku', uz: 'Qo\'rqinch', ex: 'Karanlık korkumu sonunda yendim.', step: 12},
  {tr: 'Cesaret', uz: 'Jasorat', ex: 'Önemli olan hata yapsan da deneme cesaretidir.', step: 12},
  {tr: 'Arkadaş', uz: 'Do\'st', ex: 'O benim çocukluk arkadaşım.', step: 12},
  {tr: 'Akraba', uz: 'Qarindosh', ex: 'Düğünümüze tüm akrabalarımız geldi.', step: 12},
  {tr: 'Komşu', uz: 'Qo\'shni', ex: 'Yeni komşularımız çok yardımsever.', step: 12},
  {tr: 'Misafir', uz: 'Mehmon', ex: 'Bu akşam yemeğe misafirimiz var.', step: 12},
  {tr: 'Dürüst', uz: 'To\'g\'ri so\'z (Sodiq)', ex: 'Her zaman dürüst olmalısın.', step: 12},
  {tr: 'Kibar', uz: 'Xushmuomala', ex: 'Bana karşı çok kibar davrandı.', step: 12},
  {tr: 'Yaramaz', uz: 'Sho\'x (Yomon xulqli)', ex: 'Küçük çocuk bugün çok yaramazlık yaptı.', step: 12},
  {tr: 'Zeki', uz: 'Aqlli', ex: 'Sınıfın en zeki öğrencisi o.', step: 12},

  // Step 13: Seyahat ve Ulaşım
  {tr: 'Yolculuk', uz: 'Sayohat', ex: 'Otobüs yolculuğu on saat sürdü.', step: 13},
  {tr: 'Bilet', uz: 'Chipta', ex: 'Uçak biletini internetten aldım.', step: 13},
  {tr: 'Pasaport', uz: 'Pasport', ex: 'Yurt dışına çıkmak için pasaport lazım.', step: 13},
  {tr: 'Valiz', uz: 'Chamadon', ex: 'Valizimi dün akşamdan hazırladım.', step: 13},
  {tr: 'Havalimanı', uz: 'Aeroport', ex: 'Havalimanına gitmek için taksi çağırdık.', step: 13},
  {tr: 'Otogar', uz: 'Avtovokzal', ex: 'Otogarda çok kalabalık vardı.', step: 13},
  {tr: 'Tren', uz: 'Poyezd', ex: 'Hızlı trenle Ankara\'ya gittik.', step: 13},
  {tr: 'Gemi', uz: 'Kema', ex: 'Boğazda bir gemi turu yaptık.', step: 13},
  {tr: 'Otel', uz: 'Mehmonxona', ex: 'Deniz manzaralı bir otelde kaldık.', step: 13},
  {tr: 'Rezervasyon', uz: 'Band qilish', ex: 'Restoranda akşam için rezervasyon yaptırdım.', step: 13},
  {tr: 'Turist', uz: 'Sayyoh', ex: 'Yazın buraya binlerce turist geliyor.', step: 13},
  {tr: 'Harita', uz: 'Xarita', ex: 'Yolu bulmak için haritaya baktık.', step: 13},
  {tr: 'Müze', uz: 'Muzey', ex: 'Tarihi müzeyi rehber eşliğinde gezdik.', step: 13},
  {tr: 'Rehber', uz: 'Gid (Yo\'lboshchi)', ex: 'Rehberimiz bize şehrin tarihini anlattı.', step: 13},
  {tr: 'Gezmek', uz: 'Aylanmoq (Sayohat qilmoq)', ex: 'Dünyayı gezmek en büyük hayalim.', step: 13},
  {tr: 'Fotoğraf', uz: 'Surat (Fotosurat)', ex: 'Manzaranın birkaç fotoğrafını çektim.', step: 13},
  {tr: 'Anı', uz: 'Xotira', ex: 'Bu tatilden çok güzel anılarla döndük.', step: 13},
  {tr: 'Hediyelik', uz: 'Sovg\'abop', ex: 'Arkadaşlarım için hediyelik eşya aldım.', step: 13},
  {tr: 'Yabancı', uz: 'Chet ellik (Begona)', ex: 'Şehirde birçok yabancı öğrenci var.', step: 13},
  {tr: 'Ülke', uz: 'Mamlakat', ex: 'Türkiye çok güzel bir ülkedir.', step: 13},
  {tr: 'Şehir', uz: 'Shahar', ex: 'İstanbul çok büyük ve kalabalık bir şehirdir.', step: 13},
  {tr: 'Köy', uz: 'Qishloq', ex: 'Hafta sonu köye dedemlere gittik.', step: 13},
  {tr: 'Plaj', uz: 'Plyaj', ex: 'Bütün gün plajda güneşlendik.', step: 13},
  {tr: 'Yüzme', uz: 'Suzish', ex: 'Yüzme bilmek hayat kurtarır.', step: 13},
  {tr: 'Eğlence', uz: 'O\'yin-kulgu', ex: 'Lunaparkta çok eğlendik.', step: 13},

  // Step 14: Eğitim ve Okul
  {tr: 'Okul', uz: 'Maktab', ex: 'Okul sabah sekizde başlıyor.', step: 14},
  {tr: 'Sınıf', uz: 'Sinf', ex: 'Sınıfımızda yirmi öğrenci var.', step: 14},
  {tr: 'Öğretmen', uz: 'O\'qituvchi', ex: 'Öğretmenimiz bize yeni bir konu anlattı.', step: 14},
  {tr: 'Öğrenci', uz: 'O\'quvchi', ex: 'Öğrenciler teneffüste bahçeye çıktı.', step: 14},
  {tr: 'Kitap', uz: 'Kitob', ex: 'Kütüphaneden ilginç bir kitap aldım.', step: 14},
  {tr: 'Defter', uz: 'Daftar', ex: 'Matematik dersi için yeni bir defter aldım.', step: 14},
  {tr: 'Kalem', uz: 'Qalam', ex: 'Kalemimin ucu kırıldı.', step: 14},
  {tr: 'Silgi', uz: 'O\'chirg\'ich', ex: 'Hata yaptığımda silgiyle sildim.', step: 14},
  {tr: 'Çanta', uz: 'Sumka', ex: 'Okul çantam çok ağır.', step: 14},
  {tr: 'Tahta', uz: 'Doska', ex: 'Öğretmen tahtaya bir problem yazdı.', step: 14},
  {tr: 'Ders', uz: 'Dars', ex: 'Türkçe dersini çok seviyorum.', step: 14},
  {tr: 'Ödev', uz: 'Uy vazifasi', ex: 'Akşam ödevlerimi yapmam gerekiyor.', step: 14},
  {tr: 'Sınav', uz: 'Imtihon', ex: 'Yarın çok önemli bir sınavım var.', step: 14},
  {tr: 'Not', uz: 'Baholash (Baho)', ex: 'Sınavdan yüksek bir not aldım.', step: 14},
  {tr: 'Karne', uz: 'Baholar kundaligi (Tabel)', ex: 'Dönem sonunda karnemi aldım.', step: 14},
  {tr: 'Üniversite', uz: 'Universitet', ex: 'Ağabeyim üniversitede mühendislik okuyor.', step: 14},
  {tr: 'Bölüm', uz: 'Bo\'lim (Fakultet)', ex: 'Hangi bölümde okuyorsun?', step: 14},
  {tr: 'Kütüphane', uz: 'Kutubxona', ex: 'Kütüphanede sessizce çalışmalısın.', step: 14},
  {tr: 'Okumak', uz: 'O\'qimoq', ex: 'Günde yarım saat kitap okumalıyız.', step: 14},
  {tr: 'Yazmak', uz: 'Yozmoq', ex: 'Güzel bir kompozisyon yazdım.', step: 14},
  {tr: 'Anlamak', uz: 'Tushunmoq', ex: 'Konuyu tam olarak anlamadım.', step: 14},
  {tr: 'Sormak', uz: 'So\'ramoq', ex: 'Öğretmenime bir soru sordum.', step: 14},
  {tr: 'Cevaplamak', uz: 'Javob bermoq', ex: 'Tüm soruları doğru cevapladım.', step: 14},
  {tr: 'Mezun', uz: 'Bitiruvchi', ex: 'Liseden geçen yıl mezun oldum.', step: 14},
  {tr: 'Diploma', uz: 'Diplom', ex: 'Diplomamı almak için törene katıldım.', step: 14},

  // Step 15: Spor ve Hobi
  {tr: 'Spor', uz: 'Sport', ex: 'Her sabah spor yapmaya çalışırım.', step: 15},
  {tr: 'Futbol', uz: 'Futbol', ex: 'Hafta sonları arkadaşlarımla futbol oynarım.', step: 15},
  {tr: 'Basketbol', uz: 'Basketbol', ex: 'Okulun basketbol takımındayım.', step: 15},
  {tr: 'Voleybol', uz: 'Voleybol', ex: 'Plajda voleybol oynamak çok zevkli.', step: 15},
  {tr: 'Yüzme', uz: 'Suzish', ex: 'Yazın denizde yüzmeyi özledim.', step: 15},
  {tr: 'Koşu', uz: 'Yugurish', ex: 'Sabah parkta kısa bir koşu yaptım.', step: 15},
  {tr: 'Bisiklet', uz: 'Velosiped', ex: 'Sahil yolunda bisiklet sürdük.', step: 15},
  {tr: 'Tenis', uz: 'Tennis', ex: 'Tenis oynamayı öğrenmek istiyorum.', step: 15},
  {tr: 'Satranç', uz: 'Shaxmat', ex: 'Dedemle satranç oynamayı severim.', step: 15},
  {tr: 'Müzik', uz: 'Musiqa', ex: 'En sevdiğim hobi müzik dinlemektir.', step: 15},
  {tr: 'Gitar', uz: 'Gitara', ex: 'Kursta gitar çalmayı öğreniyorum.', step: 15},
  {tr: 'Piyano', uz: 'Piyano', ex: 'Piyano sesi bana huzur veriyor.', step: 15},
  {tr: 'Resim', uz: 'Rasm', ex: 'Doğa resimleri yapmayı seviyorum.', step: 15},
  {tr: 'Dans', uz: 'Raqs', ex: 'Düğünde hep beraber dans ettik.', step: 15},
  {tr: 'Sinema', uz: 'Kinoteatr', ex: 'Bu akşam yeni bir filme gideceğiz.', step: 15},
  {tr: 'Tiyatro', uz: 'Teatr', ex: 'Şehir tiyatrosunda güzel bir oyun izledik.', step: 15},
  {tr: 'Oyun', uz: 'O\'yin', ex: 'Çocuklar bahçede oyun oynuyor.', step: 15},
  {tr: 'Koleksiyon', uz: 'Kolleksiya', ex: 'Pul koleksiyonu yapmaya başladım.', step: 15},
  {tr: 'Yürüyüş', uz: 'Sayr (Piyoda yurish)', ex: 'Akşamüstü sahilde yürüyüş yaptık.', step: 15},
  {tr: 'Kamp', uz: 'Lager (Kemping)', ex: 'Dağda çadır kurup kamp yaptık.', step: 15},
  {tr: 'Balık tutma', uz: 'Baliq ovlash', ex: 'Pazar günü balık tutmaya gideceğiz.', step: 15},
  {tr: 'Yemek yapma', uz: 'Ovqat pishirish', ex: 'Yeni yemek tarifleri denemeyi severim.', step: 15},
  {tr: 'Bahçe işleri', uz: 'Bog\'dorchilik', ex: 'Hafta sonu bahçede çiçeklerle ilgilendim.', step: 15},
  {tr: 'Fotoğrafçılık', uz: 'Fotosuratchilik', ex: 'Doğa fotoğrafçılığı hobimdir.', step: 15},
  {tr: 'Gezi', uz: 'Sayohat (Ekskursiya)', ex: 'Şehir dışına küçük bir gezi yaptık.', step: 15},

  // Step 16: Alışveriş ve Market
  {tr: 'Alışveriş', uz: 'Xaridorlik (Sotib olish)', ex: 'Bugün alışveriş merkezine gideceğiz.', step: 16},
  {tr: 'Market', uz: 'Do\'kon', ex: 'Marketten süt ve ekmek aldım.', step: 16},
  {tr: 'Bakkal', uz: 'Baqqol', ex: 'Bakkaldan bir paket tuz aldım.', step: 16},
  {tr: 'Manav', uz: 'Meva-sabzavot do\'koni', ex: 'Manavdan taze meyveler aldık.', step: 16},
  {tr: 'Kasap', uz: 'Qassob', ex: 'Kasaptan bir kilo kıyma aldım.', step: 16},
  {tr: 'Ekmek', uz: 'Non', ex: 'Taze ekmek kokusu çok güzel.', step: 16},
  {tr: 'Süt', uz: 'Sut', ex: 'Süt içmek kemikleri güçlendirir.', step: 16},
  {tr: 'Yumurta', uz: 'Tuxum', ex: 'Kahvaltıda haşlanmış yumurta yeriz.', step: 16},
  {tr: 'Peynir', uz: 'Pishloq', ex: 'Beyaz peyniri çok severim.', step: 16},
  {tr: 'Zeytin', uz: 'Zaytun', ex: 'Sofrada her zaman zeytin bulunur.', step: 16},
  {tr: 'Et', uz: 'Go\'sht', ex: 'Akşam için etli yemek pişirdim.', step: 16},
  {tr: 'Tavuk', uz: 'Tovuq', ex: 'Fırında tavuk çok lezzetli olur.', step: 16},
  {tr: 'Balık', uz: 'Baliq', ex: 'Kışın taze balık yemek sağlıklıdır.', step: 16},
  {tr: 'Sebze', uz: 'Sabzavot', ex: 'Çocuklara sebze yemeği sevdirmeliyiz.', step: 16},
  {tr: 'Meyve', uz: 'Meva', ex: 'Mevsim meyvelerini taze tüketiyoruz.', step: 16},
  {tr: 'Şeker', uz: 'Shakar', ex: 'Çayına kaç şeker atıyorsun?', step: 16},
  {tr: 'Tuz', uz: 'Tuz', ex: 'Yemek çok tuzsuz olmuş.', step: 16},
  {tr: 'Yağ', uz: 'Yog\'', ex: 'Zeytinyağı en şifalı yağdır.', step: 16},
  {tr: 'Para', uz: 'Pul', ex: 'Üstünü cüzdanıma koydum.', step: 16},
  {tr: 'Kredi kartı', uz: 'Kredit karta', ex: 'Ödemeyi kredi kartıyla yaptım.', step: 16},
  {tr: 'Nakit', uz: 'Naqd pul', ex: 'Cebimde hiç nakit para kalmadı.', step: 16},
  {tr: 'Fiş', uz: 'Chek', ex: 'Marketten sonra fişi almayı unutma.', step: 16},
  {tr: 'Fiyat', uz: 'Narx', ex: 'Bu ürünün fiyatı çok uygun.', step: 16},
  {tr: 'Poşet', uz: 'Paket (Xalta)', ex: 'Eşyaları koymak için bir poşet aldım.', step: 16},
  {tr: 'Sepet', uz: 'Savat', ex: 'Market sepetini meyvelerle doldurduk.', step: 16},

  // Step 17: Teknoloji ve Haberleşme
  {tr: 'Bilgisayar', uz: 'Kompyuter', ex: 'Ödevlerimi bilgisayarda hazırlıyorum.', step: 17},
  {tr: 'İnternet', uz: 'Internet', ex: 'Her yerde internet ulaşımı var.', step: 17},
  {tr: 'Telefon', uz: 'Telefon', ex: 'Akıllı telefonlar hayatımızı kolaylaştırdı.', step: 17},
  {tr: 'Televizyon', uz: 'Televizor', ex: 'Akşam haberlerini televizyondan izledik.', step: 17},
  {tr: 'Radyo', uz: 'Radio', ex: 'Arabada radyo dinlemeyi severim.', step: 17},
  {tr: 'Gazete', uz: 'Gazeta', ex: 'Sabah kahvaltısında gazete okurum.', step: 17},
  {tr: 'Dergi', uz: 'Jurnal', ex: 'Moda dergisini inceledim.', step: 17},
  {tr: 'Reklam', uz: 'Reklama', ex: 'Televizyonda çok uzun reklamlar çıkıyor.', step: 17},
  {tr: 'Mesaj', uz: 'Xabar', ex: 'Sana bir mesaj gönderdim, gördün mü?', step: 17},
  {tr: 'E-posta', uz: 'Elektron pochta', ex: 'İş başvurusu için e-posta yazdım.', step: 17},
  {tr: 'Sanal', uz: 'Virtual', ex: 'Sanal dünyada her şey çok hızlı.', step: 17},
  {tr: 'Şifre', uz: 'Parol (Kod)', ex: 'Şifremi kimseyle paylaşmıyorum.', step: 17},
  {tr: 'Ekran', uz: 'Ekran', ex: 'Telefonumun ekranı çizildi.', step: 17},
  {tr: 'Klavye', uz: 'Klaviatura', ex: 'Yeni klavyem çok sessiz çalışıyor.', step: 17},
  {tr: 'Fare / Mouse', uz: 'Sichqoncha (Sichqon)', ex: 'Bilgisayar faresi bozuldu.', step: 17},
  {tr: 'Yazıcı', uz: 'Printer', ex: 'Belgeleri yazıcıdan çıkarttım.', step: 17},
  {tr: 'Kamera', uz: 'Kamera', ex: 'Güvenlik kamerası her şeyi kaydetti.', step: 17},
  {tr: 'Hoparlör', uz: 'Karnay (Dinamik)', ex: 'Hoparlörden gelen ses çok yüksekti.', step: 17},
  {tr: 'Kablo', uz: 'Kabel (Sim)', ex: 'Şarj kablosunu her yere yanımda götürürüm.', step: 17},
  {tr: 'Batarya', uz: 'Batareya', ex: 'Telefonun bataryası çabuk bitiyor.', step: 17},
  {tr: 'Uygulama', uz: 'Ilova', ex: 'Yeni bir yabancı dil uygulaması indirdim.', step: 17},
  {tr: 'Site', uz: 'Sayt', ex: 'İnternet sitesi çok kullanışlı olmuş.', step: 17},
  {tr: 'Hesap', uz: 'Hisob', ex: 'Sosyal medya hesabımı kapattım.', step: 17},
  {tr: 'Takipçi', uz: 'Obunachi (Kuzatuvchi)', ex: 'Onun çok fazla takipçisi var.', step: 17},
  {tr: 'Bağlantı', uz: 'Bog\'lanish (Aloqa)', ex: 'İnternet bağlantısı koptu.', step: 17},

  // Step 18: Şehir ve Mekanlar
  {tr: 'Şehir', uz: 'Shahar', ex: 'Şehir merkezi akşamları çok canlı.', step: 18},
  {tr: 'Mahalle', uz: 'Mahalla', ex: 'Bizim mahallemiz çok huzurludur.', step: 18},
  {tr: 'Sokak', uz: 'Ko\'cha', ex: 'Sokakta çocuklar top oynuyor.', step: 18},
  {tr: 'Cadde', uz: 'Shox ko\'cha (Prospekt)', ex: 'Ana caddede trafik çok yoğun.', step: 18},
  {tr: 'Meydan', uz: 'Maydon', ex: 'Şehir meydanında bir heykel var.', step: 18},
  {tr: 'Park', uz: 'Bog\' (Park)', ex: 'Çocuk parkına gidip eğlendik.', step: 18},
  {tr: 'Bina', uz: 'Bino', ex: 'Yeni yapılan bina çok yüksek görünüyordu.', step: 18},
  {tr: 'Apartman', uz: 'Ko\'p qavatli uy', ex: 'Apartman girişinde çiçekler var.', step: 18},
  {tr: 'Ofis', uz: 'Ofis (Idora)', ex: 'Bugün ofis çok sessiz.', step: 18},
  {tr: 'Banka', uz: 'Bank', ex: 'Bankadan para çekmem lazım.', step: 18},
  {tr: 'Postane', uz: 'Pochta', ex: 'Postaneden bir paket gönderdim.', step: 18},
  {tr: 'Kütüphane', uz: 'Kutubxona', ex: 'Hafta içi kütüphanede ders çalışırım.', step: 18},
  {tr: 'Sinema', uz: 'Kinoteatr', ex: 'Sinemanın önünde buluştuk.', step: 18},
  {tr: 'Kafeterya', uz: 'Oshxona (Kafe)', ex: 'Kafeteryada bir fincan çay içtik.', step: 18},
  {tr: 'Restoran', uz: 'Restoran', ex: 'Şık bir restoranda akşam yemeği yedik.', step: 18},
  {tr: 'Karakol', uz: 'Politsiya bo\'limi', ex: 'Cüzdanımı kaybedince karakola gittim.', step: 18},
  {tr: 'Belediye', uz: 'Hokimiyat (Shahar boshqarmasi)', ex: 'Belediye parkı yeniden düzenledi.', step: 18},
  {tr: 'Durak', uz: 'Bekat', ex: 'Otobüs durağında on dakika bekledim.', step: 18},
  {tr: 'İstasyon', uz: 'Stansiya', ex: 'Tren istasyonu çok kalabalıktı.', step: 18},
  {tr: 'Liman', uz: 'Port (Pristan)', ex: 'Gemi az önce limana yanaştı.', step: 18},
  {tr: 'Köprü', uz: 'Ko\'prik', ex: 'Köprüden geçerken manzarayı izledik.', step: 18},
  {tr: 'Havuz', uz: 'Hovuz', ex: 'Sıcak havalarda havuzda yüzmek güzel.', step: 18},
  {tr: 'Cami', uz: 'Masjid', ex: 'Tarihi camiyi ziyarete gittik.', step: 18},
  {tr: 'Kilise', uz: 'Cherkov', ex: 'Eski kilisenin mimarisi çok etkileyici.', step: 18},
  {tr: 'Okul', uz: 'Maktab', ex: 'Evimiz okula çok uzak değil.', step: 18},

  // Step 19: Sosyal Hayat ve Kültür
  {tr: 'Kültür', uz: 'Madaniyat', ex: 'Farklı kültürleri tanımayı severim.', step: 19},
  {tr: 'Sanat', uz: 'San\'at', ex: 'Müzedeki sanat eserleri muazzamdı.', step: 19},
  {tr: 'Müzik', uz: 'Musiqa', ex: 'Klasik müzik ruhu dinlendirir.', step: 19},
  {tr: 'Edebiyat', uz: 'Adabiyot', ex: 'Üniversitede Türk edebiyatı okuyor.', step: 19},
  {tr: 'Tarih', uz: 'Tarix', ex: 'Kentin tarihini anlatan bir kitap okudum.', step: 19},
  {tr: 'Gelenek', uz: 'An\'ana', ex: 'Geleneklerimize saygı göstermeliyiz.', step: 19},
  {tr: 'Bayram', uz: 'Bayram', ex: 'Ramazan bayramında tatlılar yaptık.', step: 19},
  {tr: 'Düğün', uz: 'To\'y', ex: 'Hafta sonu çok yakın bir arkadaşımın düğünü var.', step: 19},
  {tr: 'Doğum günü', uz: 'Tug\'ilgan kun', ex: 'Doğum günümü arkadaşlarla kutladık.', step: 19},
  {tr: 'Eğlence', uz: 'O\'yin-kulgu', ex: 'Tatil köyünde her akşam eğlence vardı.', step: 19},
  {tr: 'Konser', uz: 'Konsert', ex: 'Bu akşam açık hava konserine gideceğiz.', step: 19},
  {tr: 'Sergi', uz: 'Ko\'rgazma', ex: 'Resim sergisini hayranlıkla gezdik.', step: 19},
  {tr: 'Moda', uz: 'Moda', ex: 'Son yılların modasını takip ediyorum.', step: 19},
  {tr: 'Sinema', uz: 'Kino', ex: 'Sinemaya gitmeyi çok seviyorum.', step: 19},
  {tr: 'Tiyatro', uz: 'Teatr', ex: 'Eski bir tiyatro sahnesinde gösteri yapıldı.', step: 19},
  {tr: 'Siyaset', uz: 'Siyosat', ex: 'Siyaset programlarını ilgiyle izlerim.', step: 19},
  {tr: 'Ekonomi', uz: 'Iqtisodiyot', ex: 'Gazetelerin ekonomi sayfasını okudum.', step: 19},
  {tr: 'Gündem', uz: 'Kun tartibi (Muhim voqea)', ex: 'Bugünkü gündemimiz yeni projeler.', step: 19},
  {tr: 'Haber', uz: 'Xabar (Yangilik)', ex: 'Akşam haberlerini pür dikkat dinledi.', step: 19},
  {tr: 'Toplum', uz: 'Jamiyat', ex: 'Toplum kurallarına uymak gerekir.', step: 19},
  {tr: 'İnsanlar', uz: 'Odamlar', ex: 'Parkta birçok insanlar güneşin tadını çıkarıyor.', step: 19},
  {tr: 'Gençlik', uz: 'Yoshlik', ex: 'Ülkenin geleceği gençliktedir.', step: 19},
  {tr: 'Çocukluk', uz: 'Bolalik', ex: 'Çocukluk yıllarımı hasretle özlüyorum.', step: 19},
  {tr: 'Yaşlılık', uz: 'Qarilik', ex: 'Yaşlılıkta huzur bulmak çok önemli.', step: 19},
  {tr: 'Saygı', uz: 'Hurmat', ex: 'Küçüklere sevgi, büyüklere saygı göstermeliyiz.', step: 19},

  // Step 20: Soyut Kavramlar ve Sıfatlar
  {tr: 'Doğru', uz: 'To\'g\'ri', ex: 'Her zaman doğruyu söylemek dürüstlüktür.', step: 20},
  {tr: 'Yanlış', uz: 'Noto\'g\'ri', ex: 'Ödevimdeki yanlışları sildim.', step: 20},
  {tr: 'İyi', uz: 'Yaxshi', ex: 'Kendimi bugün çok iyi hissediyorum.', step: 20},
  {tr: 'Kötü', uz: 'Yomon', ex: 'Kötü gün dostuna her zaman ihtiyaç vardır.', step: 20},
  {tr: 'Hızlı', uz: 'Tez', ex: 'Araba o kadar hızlıydı ki göremedim.', step: 20},
  {tr: 'Yavaş', uz: 'Sekin', ex: 'Kaplumbağalar çok yavaş yürürler.', step: 20},
  {tr: 'Ağır', uz: 'Og\'ir', ex: 'Poşetler çok ağır, yardım eder misin?', step: 20},
  {tr: 'Hafif', uz: 'Yengil', ex: 'Bulutlar gökyüzünde hafifçe süzülüyor.', step: 20},
  {tr: 'Sert', uz: 'Qattiq', ex: 'Yastık çok sert, uyuyamadım.', step: 20},
  {tr: 'Yumuşak', uz: 'Yumshoq', ex: 'Yeni battaniyem çok yumuşak.', step: 20},
  {tr: 'Acı', uz: 'Achchiq', ex: 'Biber çok acı çıktı.', step: 20},
  {tr: 'Tatlı', uz: 'Shirin', ex: 'Bu kek gerçekten çok tatlı olmuş.', step: 20},
  {tr: 'Sıcak', uz: 'Issiq', ex: 'Kahvem çok sıcak, biraz beklemeliyim.', step: 20},
  {tr: 'Soğuk', uz: 'Sovuq', ex: 'Soğuk havalarda dondurma yenmez.', step: 20},
  {tr: 'Zengin', uz: 'Boy (Badavlat)', ex: 'Onun çok zengin bir hayal dünyası var.', step: 20},
  {tr: 'Fakir', uz: 'Kambag\'al', ex: 'İnsanlara yardım etmek kalbi zenginleştirir.', step: 20},
  {tr: 'Akıllı', uz: 'Aqlli', ex: 'Kedimiz gerçekten çok akıllı bir hayvan.', step: 20},
  {tr: 'Aptal', uz: 'Ahmoq', ex: 'Aynı hatayı iki kez yapmak pek hoş değil.', step: 20},
  {tr: 'Cesur', uz: 'Jasur', ex: 'Cesur askerler vatanı koruyor.', step: 20},
  {tr: 'Korkak', uz: 'Qo\'rqoq', ex: 'Karanlıktan korkan korkak biri değilim.', step: 20},
  {tr: 'Önemli', uz: 'Muhim', ex: 'Yarın çok önemli bir randevum var.', step: 20},
  {tr: 'Luzumsuz', uz: 'Befoyda', ex: 'Luzumsuz eşyaları tavan arasına kaldırdım.', step: 20},
  {tr: 'Net', uz: 'Aniq', ex: 'Soruna net bir cevap verdi.', step: 20},
  {tr: 'Karışık', uz: 'Murakkab (Chigal)', ex: 'Yol tarifi biraz karışık görünüyordu.', step: 20},
  {tr: 'Sürpriz', uz: 'Syurpriz', ex: 'Arkadaşım bana küçük bir sürpriz yaptı.', step: 20}
];

batch.forEach((item, index) => {
  words.push({
    id: `p-a1s${item.step}-${index}`,
    tr: item.tr,
    uz: item.uz,
    example: item.example,
    level: 'A1',
    step: item.step
  });
});

fs.writeFileSync('words.json', JSON.stringify(words, null, 2));
console.log('Batch 5-8 Added Successfully');
