services:
  - type: web
    name: turkishly-bot
    runtime: node
    plan: free
    buildCommand: "npm install && cd mini-app && npm install && npm run build && cd .."
    startCommand: "node index.js"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: NODE_ENV
        value: production
